/**
 * Standalone, client-side port of backend/pipeline.py + backend/kb.py.
 *
 * This is a byte-for-byte behavioral mirror of the real Python pipeline —
 * same thresholds, same scoring formula, same risk/reason/recommendation
 * structure, same retrieval algorithm — so the standalone demo produces
 * identical results to the FastAPI backend for the same input. The
 * knowledge base data below (kbBundle) was generated by running the real,
 * unmodified kb.py, not re-typed by hand.
 */
import kbBundle from './kb_bundle.json'

// ---------------------------------------------------------------------
// DEMO / PROTOTYPE LOGIC — identical to backend/pipeline.py DEMO_THRESHOLDS
// ---------------------------------------------------------------------
const DEMO_THRESHOLDS = {
  capital_adequacy_ratio_min: 10.5,
  liquidity_ratio_min: 90,
  npl_ratio_max: 5.0,
  operating_margin_min: 0.15,
}

const STOPWORDS = new Set([
  'the', 'a', 'an', 'and', 'or', 'of', 'to', 'in', 'for', 'on', 'is', 'are',
  'be', 'this', 'that', 'with', 'as', 'by', 'it', 'not', 'official', 'text',
])

function tokenize(text) {
  const words = (text.toLowerCase().match(/[a-z0-9_]+/g) || [])
  return words.filter((w) => !STOPWORDS.has(w) && w.length > 2)
}

// Mirrors kb.py retrieve(query, top_k)
function retrieve(query, topK = 3) {
  const queryTokens = new Set(tokenize(query))
  const scored = []
  for (const s of kbBundle.summaries) {
    const docTokens = new Set([...tokenize(s.text), ...s.topics])
    let score = 0
    for (const t of queryTokens) if (docTokens.has(t)) score += 1
    if (score > 0) scored.push([score, s])
  }
  scored.sort((a, b) => b[0] - a[0])
  return scored.slice(0, topK).map(([, s]) => s)
}

// --- SRC ---------------------------------------------------------------
function srcIngest(raw) {
  return { ...raw }
}

// --- C -------------------------------------------------------------------
function collectorCollect(src) {
  return { submitted_at: new Date().toISOString(), raw: src }
}

// --- PP ------------------------------------------------------------------
function preprocessorNormalize(collected) {
  const raw = collected.raw
  const num = (key, def = 0) => {
    const v = Number(raw[key])
    return Number.isFinite(v) ? v : def
  }
  const revenue = num('annual_revenue')
  const opex = num('operating_costs')
  const operatingMargin = revenue > 0 ? (revenue - opex) / revenue : 0

  return {
    institution_type: raw.institution_type || 'unspecified',
    product: raw.product || 'unspecified',
    target_market: raw.target_market || 'unspecified',
    annual_revenue: revenue,
    operating_costs: opex,
    operating_margin: Math.round(operatingMargin * 10000) / 10000,
    capital_adequacy_ratio: num('capital_adequacy_ratio'),
    liquidity_ratio: num('liquidity_ratio'),
    npl_ratio: num('npl_ratio'),
    submitted_at: collected.submitted_at,
  }
}

// --- M ---------------------------------------------------------------
function modelScore(clean) {
  const th = DEMO_THRESHOLDS
  const clamp = (x) => Math.max(0, Math.min(100, x))

  const profitabilityScore = clamp((clean.operating_margin / th.operating_margin_min) * 100)
  const capitalScore = clamp((clean.capital_adequacy_ratio / th.capital_adequacy_ratio_min) * 100)
  const liquidityScore = clamp((clean.liquidity_ratio / th.liquidity_ratio_min) * 100)
  const nplScore = clamp((1 - clean.npl_ratio / th.npl_ratio_max) * 100)

  const overall = Math.round(
    (0.25 * profitabilityScore + 0.25 * capitalScore + 0.25 * liquidityScore + 0.25 * nplScore) * 10
  ) / 10

  return {
    overall_score: overall,
    sub_scores: {
      profitability_score: Math.round(profitabilityScore * 10) / 10,
      capital_score: Math.round(capitalScore * 10) / 10,
      liquidity_score: Math.round(liquidityScore * 10) / 10,
      npl_score: Math.round(nplScore * 10) / 10,
    },
    thresholds_used: th,
  }
}

// --- P -------------------------------------------------------------------
function policyApply(clean, modelOut) {
  const th = DEMO_THRESHOLDS
  const overall = modelOut.overall_score
  const riskLevel = overall >= 75 ? 'Low' : overall >= 50 ? 'Medium' : 'High'

  const financialRisks = []

  if (clean.capital_adequacy_ratio < th.capital_adequacy_ratio_min) {
    financialRisks.push({
      risk: 'Capital adequacy risk',
      reason: `Capital adequacy ratio (${clean.capital_adequacy_ratio}%) is below the configured demo readiness threshold (${th.capital_adequacy_ratio_min}%).`,
      recommendation: 'Strengthen capital position before launch, or phase the rollout to reduce initial capital exposure.',
      logic_type: 'Demo / Prototype Logic',
    })
  }
  if (clean.liquidity_ratio < th.liquidity_ratio_min) {
    financialRisks.push({
      risk: 'Liquidity risk',
      reason: `Liquidity ratio (${clean.liquidity_ratio}%) is below the configured demo readiness threshold (${th.liquidity_ratio_min}%).`,
      recommendation: 'Improve liquidity coverage before launching the proposed product.',
      logic_type: 'Demo / Prototype Logic',
    })
  }
  if (clean.npl_ratio > th.npl_ratio_max) {
    financialRisks.push({
      risk: 'Credit / non-performing loans risk',
      reason: `NPL ratio (${clean.npl_ratio}%) exceeds the configured demo readiness threshold (${th.npl_ratio_max}%).`,
      recommendation: 'Review credit risk controls and provisioning before expanding into the target market.',
      logic_type: 'Demo / Prototype Logic',
    })
  }
  if (clean.operating_margin < th.operating_margin_min) {
    financialRisks.push({
      risk: 'Profitability / cost-structure risk',
      reason: `Operating margin (${(clean.operating_margin * 100).toFixed(1)}%) is below the configured demo readiness threshold (${(th.operating_margin_min * 100).toFixed(0)}%).`,
      recommendation: 'Reassess the cost base or revenue assumptions for the proposed product before launch.',
      logic_type: 'Demo / Prototype Logic',
    })
  }

  const query = `${clean.product} ${clean.target_market} ${clean.institution_type}`
  const retrievedGroups = retrieve(query, 3)

  const regulatoryFindings = []
  for (const group of retrievedGroups) {
    for (const src of group.sources) {
      regulatoryFindings.push({
        risk: `Regulatory review needed — ${src.authority}`,
        reason: `The proposed product/market touches topics covered by ${src.authority}'s official guidance (${group.topics.slice(0, 3).join(', ')}).`,
        recommendation: `Review ${src.title} before launch to confirm compliance.`,
        evidence: {
          title: src.title,
          authority: src.authority,
          url: src.url,
          type: src.type,
          status: src.status,
          manual_verification_recommended: !!src.manual_verification_recommended,
        },
      })
    }
  }

  return { risk_level: riskLevel, financial_risks: financialRisks, regulatory_findings: regulatoryFindings }
}

// --- D -------------------------------------------------------------------
function distributorFormat(clean, modelOut, policyOut) {
  const recommendations = []
  for (const r of policyOut.financial_risks) recommendations.push(r.recommendation)
  for (const r of policyOut.regulatory_findings) recommendations.push(r.recommendation)
  if (recommendations.length === 0) {
    recommendations.push('No material risks detected against the configured demo thresholds. Proceed with standard due diligence.')
  }

  const seen = new Set()
  const evidence = []
  for (const r of policyOut.regulatory_findings) {
    if (!seen.has(r.evidence.url)) {
      evidence.push(r.evidence)
      seen.add(r.evidence.url)
    }
  }

  return {
    generated_at: clean.submitted_at,
    input_summary: {
      institution_type: clean.institution_type,
      product: clean.product,
      target_market: clean.target_market,
      annual_revenue: clean.annual_revenue,
      operating_costs: clean.operating_costs,
      capital_adequacy_ratio: clean.capital_adequacy_ratio,
      liquidity_ratio: clean.liquidity_ratio,
      npl_ratio: clean.npl_ratio,
    },
    readiness_score: modelOut.overall_score,
    risk_level: policyOut.risk_level,
    sub_scores: modelOut.sub_scores,
    thresholds_used: modelOut.thresholds_used,
    financial_risks: policyOut.financial_risks,
    regulatory_findings: policyOut.regulatory_findings,
    recommendations,
    evidence,
    disclaimer:
      "FinShield is a decision-support prototype for the ITU AI Readiness 2.0 Hackathon. It is NOT a certified financial or regulatory assessment tool and does not replace professional financial or legal judgment. All numeric thresholds are labeled 'Demo / Prototype Logic' and are illustrative only.",
  }
}

// --- Orchestrator (MLFO role) -------------------------------------------
export function runPipeline(rawInput) {
  const src = srcIngest(rawInput)
  const collected = collectorCollect(src)
  const clean = preprocessorNormalize(collected)
  const modelOut = modelScore(clean)
  const policyOut = policyApply(clean, modelOut)
  return distributorFormat(clean, modelOut, policyOut)
}

export function getDemoInstitutions() {
  return kbBundle.demo_institutions
}

export function getSources() {
  return kbBundle.sources
}
